"""Tipo de campo alterado processos

Revision ID: 686dc86f3b9c
Revises: 4d6b64b6cfb1
Create Date: 2022-01-06 09:06:19.106498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686dc86f3b9c'
down_revision = '4d6b64b6cfb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
