"""Ramal e Em Férias adicionado a Person

Revision ID: a3de899d3d6d
Revises: 686dc86f3b9c
Create Date: 2022-01-07 18:19:42.263582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3de899d3d6d'
down_revision = '686dc86f3b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('work_phone', sa.String(length=255), nullable=True))
    op.add_column('person', sa.Column('on_vacation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'on_vacation')
    op.drop_column('person', 'work_phone')
    # ### end Alembic commands ###
